import { getAsyncActionTypes } from '../reduxHelpers'

export const UPDATE_DEFAULT_USER_SCREEN = getAsyncActionTypes(
  'UPDATE_DEFAULT_USER_SCREEN')
export const GET_DEFAULT_USER_SCREEN = getAsyncActionTypes(
  'GET_DEFAULT_USER_SCREEN')
export const SET_SHOW_POP_ADD_CHECK = 'SET_SHOW_POP_ADD_CHECK'
export const SET_REMEMBER_ME = 'SET_REMEMBER_ME'
export const SET_TIMES_OF_TARYE = 'SET_TIMES_OF_TARYE'
export const SET_SHOW_POP_ADD_CASH = 'SET_SHOW_POP_ADD_CASH'
export const SET_SHOW_POP_ADD_TRANS = 'SET_SHOW_POP_ADD_TRANS'
export const SET_TIMES_OF_MUTAVIM = 'SET_TIMES_OF_MUTAVIM'
export const SET_IF_OPEN_BOTTOM_SHEET = 'SET_IF_OPEN_BOTTOM_SHEET'
export const GLOBAL_PARAMS = 'GLOBAL_PARAMS'
